/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
         TestCases tests = new TestCases(); // Initialize your test class
         Search_Amazon Search_Amazon = new Search_Amazon();
         Hyperlinks_count Hyperlinks_count=new Hyperlinks_count();
        LinkedIN LinkedIN= new LinkedIN();
        Activity5_Automate_image_urls Activity5= new Activity5_Automate_image_urls();
         Activity7_Automate_nested_frames_text Activity7=new Activity7_Automate_nested_frames_text();
        Avtivity9_IMDB Activity9 = new Avtivity9_IMDB();
        Activity10Automate_window_handle act10=new Activity10Automate_window_handle();

        // TODO: call your test case functions one after other here

        Search_Amazon.testCase01();
        Hyperlinks_count.testCase01();
         LinkedIN.testCase01();
         Activity5.testCase01();
         Activity7.testCase01();
        
        Activity9.testCase01();
        act10.testCase01();

        // END Tests

        Search_Amazon.endTest();
        Hyperlinks_count.endTest();
        LinkedIN.endTest();
        Activity5.endTest();// End your test by clearning connections and closing
        // browser
        Activity7.endTest();
       Activity9.endTest();
       act10.endTest();

    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
